[package]
name = 'cosmicsloth/testing'
version = '0.0.5'
description = 'This is a test'

# See more keys and definitions at https://docs.wasmer.io/registry/manifest

[dependencies]

[[module]]
name = 'testing'
source = 'target/wasm32-unknown-unknown/debug/rusty_sorter.wasm'
abi = 'none'


[[binding]]
name = 'testing'
module = 'testing'
